# Generated by Django 2.2.15 on 2020-08-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_task_show_details"),
        ("submit", "0005_auto_20190705_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitreceiver",
            name="task_new",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submit_receivers_new",
                to="tasks.Task",
                null=True,
            ),
            preserve_default=False,
        ),
    ]
