# Generated by Django 2.2.15 on 2020-08-08 13:32

from django.db import migrations


def make_submitreceiver_task(apps, schema_editor):
    Submitreceiver = apps.get_model("submit", "SubmitReceiver")

    for submitreceiver in Submitreceiver.objects.all():
        tasks = submitreceiver.task_set.all()
        if tasks:
            submitreceiver.task_new = tasks.first()
            submitreceiver.save()


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0006_submitreceiver_task_new"),
    ]

    operations = [
        migrations.RunPython(make_submitreceiver_task),
    ]
