# Generated by Django 2.2.15 on 2020-08-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_remove_task_submit_receivers"),
        ("submit", "0007_auto_20200808_1532"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submitreceiver", old_name="task_new", new_name="task",
        ),
    ]
