# Generated by Django 2.0.13 on 2024-02-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_auto_20200808_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='reference_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
