# Generated by Django 5.0.7 on 2024-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_auto_20200808_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitreceiver',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submitreceivertemplate',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
    ]
