# Generated by Django 3.2.10 on 2021-12-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_auto_20200808_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitreceiver',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submitreceivertemplate',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
    ]
