# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-18 12:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_auto_20180705_1333"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="contests",
            field=models.ManyToManyField(related_name="contests", to="tasks.Contest"),
        ),
        migrations.AlterField(
            model_name="task",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest",
                to="tasks.Contest",
            ),
        ),
    ]
