# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-18 12:10
from __future__ import unicode_literals

from django.db import migrations


def make_many_contests(apps, schema_editor):
    """
        Adds the Contest object in Task to the
        many-to-many relationship in Contests
    """
    Task = apps.get_model('tasks', 'Task')

    for task in Task.objects.all():
        task.contests.add(task.contest)



class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200318_1310'),
    ]

    operations = [
        migrations.RunPython(make_many_contests),
    ]
