# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contests',
            field=models.ManyToManyField(related_name='tasks', to='tasks.Contest'),
        ),
    ]
