# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200318_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contests',
            field=models.ManyToManyField(related_name='task_set', to='tasks.Contest'),
        ),
    ]
