# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-18 14:00
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200318_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='task_set_new',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='contests_new', to='tasks.Task'),
        ),
    ]
