# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-18 14:00
from __future__ import unicode_literals

from django.db import migrations


def make_task_contests(apps, schema_editor):
    Contest = apps.get_model("tasks", "Contest")

    for contest in Contest.objects.all():
        for task in contest.task_set.order_by("number"):
            contest.task_set_new.add(task)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_contest_task_set_new"),
    ]

    operations = [
        migrations.RunPython(make_task_contests),
    ]
