# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-18 14:06
from __future__ import unicode_literals

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_remove_task_contests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="task_set_new",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, related_name="contests", to="tasks.Task"
            ),
        ),
    ]
