# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-03-18 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20200318_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='task_set_new',
            new_name='task_set',
        ),
    ]
