# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-04-29 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_auto_20200318_1506"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="show_details",
            field=models.BooleanField(default=False),
        ),
    ]
