# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.CharField(max_length=1024),
        ),
    ]
